# Generated by Django 4.0.3 on 2022-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='img',
            field=models.ImageField(help_text='The image should be: 600*600', upload_to='employee/'),
        ),
    ]
